config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#index'

  resources :users, only: [:show]

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/activity.rb
class Activity < OpenStruct

  def self.service(user)
    @service ||= ActivityService.new(user)
  end

  def self.user_activity(user)
    activities_hash = service(user).get_user_activity
    activities = activities_hash.map { |activity| Activity.new(activity) }
    self.sort_activities(activities)
  end

  def self.followings_activity(user)
    activities_hash = service(user).get_followings_activity
    activities = activities_hash.map { |activity| Activity.new(activity) }
    self.sort_activities(activities)
  end

  def self.sort_activities(activities)
    commits = activities.select do |activity|
      activity[:type] == "PushEvent" && activity.payload['commits'].first
    end
    commits.sort_by { |data| data[:created_at] }.reverse
  end

  def commit_message
    payload['commits'].first.message
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github_user.rb
class GithubUser < OpenStruct

  def self.service(user)
    @service ||= GithubUserService.new(user)
  end

  def self.find(user)
    user_hash = service(user).get_github_user
    GithubUser.new(user_hash)
  end

  def self.followings(user)
    followings_hash = service(user).get_followings
    followings_hash.map { |following| GithubUser.new(following) }
  end
end

app/models/organization.rb
class Organization < OpenStruct

  def self.service(user)
    @service ||= OrganizationService.new(user)
  end

  def self.organizations(user)
    orgs = service(user).get_organizations
    orgs.map do |org|
      Organization.new(org)
    end
  end
end

app/models/repo.rb
class Repo < OpenStruct

  def self.service(user)
    RepoService.new(user)
  end

  def self.user_repos(user)
    repos = service(user).get_user_repos
    repos.map do |repo|
      Repo.new(repo)
    end
  end

  def self.starred_repos(user)
    starred_repos = service(user).get_starred_repos
    starred_repos.map do |starred_repo|
      Repo.new(starred_repo)
    end
  end

  def self.count(user)
    self.starred_repos(user).count
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid      = auth_info.uid
      new_user.provider = auth_info.provider
      new_user.username = auth_info.extra.raw_info.login
      new_user.name     = auth_info.info.name
      new_user.token    = auth_info.credentials.token
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = GithubUser.find(current_user)
    @starred_repos = Repo.count(current_user)
    @repos = Repo.user_repos(current_user)
    @user_activity = Activity.user_activity(current_user)
    @followings_activity = Activity.followings_activity(current_user)
    @organizations = Organization.organizations(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

   def format_date(time)
     Date.parse(time).strftime("%b %d, %Y")
   end
end

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
        WITHUB
    </a>
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li>
          <%= link_to "Logged in as #{current_user.name}", user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Logout", logout_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Login with Github", github_login_path %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apicurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/root/index.html.erb
<div class="container">
  <div class='text-center well'>
    <h1>Welcome to Withub </h1>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">
   <div class="col-md-3">
     <img id="user-image" src="<%= @user.avatar_url %>">
     <br>
     <h2 id="username"><%= @user.login %></h2>
     <h5 id="user-full-name"><%= @user.name %></h5>
     <br>
     <p>Followers: <%= @user.followers %></p>
     <p>Starred: <%= @starred_repos %></p>
     <p>Following: <%= @user.following %></p>
   </div>
    <div id="github-categories" class="col-md-9 text-center">
      <h1>My Repositories</h1>
      <ul class="list-group">
        <% @repos.each do |repo| %>
          <li class="list-group-item"><%= repo.name %></li>
        <% end %>
      </ul>
      <br>
      <h1>My Organizations</h1>
      <ul class="list-group">
        <% @organizations.each do |organization| %>
        <li class="list-group-item">
          <%= image_tag(organization.avatar_url, size: "70x70") %> <%= organization.login %>
        </li>
        <% end %>
      </ul>
      <br>
      <h1>Recent Activity of People I Follow</h1>
      <table class='table table-striped table-bordered'>
            <tr>
              <th class='text-center'>Date</th>
              <th class='text-center'>User</th>
              <th class='text-center'>Repo</th>
              <th class='text-center'>Commit Message</th>
            </tr>
        <% @followings_activity.each do |activity| %>
            <tr>
              <td style="width: 110px;"><%= format_date(activity.created_at)%></td>
              <td><%= activity.actor.login %></td>
              <td><%= activity.repo.name %></td>
              <td><%= activity.commit_message %></td>
            </tr>
        <% end %>
      </table>
      <br>
      <h1>My Recent Activity</h1>
      <table class="table table-striped table-bordered">
          <tr>
            <th class='text-center'>Date</th>
            <th class='text-center'>Repo</th>
            <th class='text-center'>Commit Message</th>
          </tr>
        <% @user_activity.each do |activity| %>
          <tr>
            <td style="width: 110px;"><%= format_date(activity.created_at) %></td>
            <td><%= activity.repo.name %></td>
            <td><%= activity.commit_message %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>